name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        ~/.poetry/bin/poetry --version
        pip install poetry-dynamic-versioning
    - name: Install dependencies
      run: |
        ~/.poetry/bin/poetry install
    - name: Build package
      run: |
        ~/.poetry/bin/poetry build
    - name: Publish package
      run: |
        ~/.poetry/bin/poetry config repositories.artifactory https://artifactory.glovoint.com/artifactory/api/pypi/pypi-local
        ~/.poetry/bin/poetry publish --repository artifactory --username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}